### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by ravimantra** [jjhbw/barcode-scanner-webassembly#3]
<img width="1679" alt="Screen Shot 2019-04-15 at 12 08 32 PM" src="https://user-images.githubusercontent.com/11537752/56112034-78909900-5f77-11e9-8eb8-51df9569c94d.png">
 Can you please suggest me on the same ?

**Comment by jjhbw** [comment]
It seems the answer is in the first error: when a route represents a different origin than the script/file you are requesting it from, the browser only executes the request if that route is HTTP/HTTPS. It refuses to read directly from a file for safety reasons.

See the docs for [the CORS mechanism](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

In short: use a web server.
